image: maven:3.6.1-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode -e"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test